"""add storage_used and storage_quota_bytes to users

Revision ID: 9202e1c08268
Revises: 6af390c692fa
Create Date: 2026-08-09 15:18:50.701584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9202e1c08268'
down_revision: Union[str, None] = '6af390c692fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
