"""add storage_quota to users

Revision ID: b5a4903a8389
Revises: c79f0216da3a
Create Date: 2026-08-14 03:37:47.320125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a4903a8389'
down_revision: Union[str, None] = 'c79f0216da3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_quota_bytes', sa.BigInteger(), server_default='5368709120', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_quota_bytes')
    # ### end Alembic commands ###
