"""add upload to users

Revision ID: 0613f236bb72
Revises: b5a4903a8389
Create Date: 2026-08-14 21:02:56.040675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0613f236bb72'
down_revision: Union[str, None] = 'b5a4903a8389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('upload_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'upload_id')
    # ### end Alembic commands ###
