"""add storage_used to users

Revision ID: 1ad4e3a557bb
Revises: 35c79265eee0
Create Date: 2026-08-09 15:03:22.348455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad4e3a557bb'
down_revision: Union[str, None] = '35c79265eee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_used', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_used')
    # ### end Alembic commands ###
